<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<style>
    .margin_top{
        margin-top: 150px;

    }
    body{
        width: 100%;
    }
</style>
<body>
<div class="container-fluid">
    <?php echo $this->getContent(); ?>
</div>
</body>
</html>